# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Łukasz Jałocha
title: Backend Software Engineer
email: lukaszjalocha55@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  dezo505
linkedin_username: lukasz-jalocha

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  **Java Backend Software Engineer** focused on building scalable and reliable backend systems.
  I work with **Java**/**Kotlin**, **Spring Boot**, **microservices**, and **cloud technologies**, creating clean, maintainable code and well-designed backend architectures. On a daily basis, I contribute to Agile development workflows, collaborate closely with my team, and continuously develop my skills to deliver efficient and robust solutions.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: EPAM Systems
        sub_title: Software Engineer
        caption: January 2025 - Present
        description: |
          At EPAM, I work as a Software Engineer in a team focused on **modernizing and migrating large-scale enterprise systems**. I contribute across **multiple repositories**, implementing new features, improving existing components, and ensuring alignment with **architectural guidelines**. I collaborate closely with other developers and actively participate in **Agile ceremonies** to support efficient delivery and continuous improvement.

      - layout: left
        title: Grid Dynamics
        sub_title: Junior Software Engineer
        caption: February 2024 - December 2024
        description: |
          At Grid Dynamics, I worked on both long-term **API maintenance** and a cross-functional initiative delivering a **new feature** within a **distributed system**. I implemented new functionality, improved **application stability**, documented technical processes, and performed code reviews. I collaborated daily with a global, **internationally distributed team**, coordinating work across multiple time zones and cultures, which strengthened my communication and teamwork skills in a remote-first environment.

      - layout: left
        title: Capgemini
        sub_title: Software Engineer Intern
        caption: May 2022 - April 2023
        description: |
          During my internship at Capgemini, I completed a structured **backend development learning path** and worked as a backend developer on an **internal productivity-enhancing project**. I supported the team by preparing detailed **technical documentation** and participating in the full **Agile** Scrum workflow. This role provided me with a solid **foundation in backend engineering** and collaborative software development.

  - title: Core Skills
    layout: list
    content:
      - layout: left
        title: Technical Skills
        description: |
          - Java / Kotlin
          - Spring Boot
          - Gradle / Maven
          - Google Cloud Platform & Azure
          - Docker
          - SQL / MongoDb
          - Microservices Architecture
          - REST API
          - Git
      - layout: left
        title: Language
        description: |
          - Polish - **Native**
          - English - **C1**
          - Spanish - **A2**

  - title: Certificates
    layout: text
    content: |
      - **Google**, Google Cloud Certified - Associate Cloud Engineer (2024)
      - **Microsoft**, Microsoft Certified - Azure Fundamentals (2023)

  - title: Education
    layout: list
    content:
      - layout: left
        title: Wrocław University of Science and Technology (PWr)
        caption: 2021 - 2025
        sub_title: BSc (inż.) Computer Science
        description: |
          During my studies at PWr, I built strong foundations in software engineering, algorithms, distributed systems, and backend development.
          
          As part of my engineering group project, I co-created **Ear Defender**, a multi-container audio-analysis platform that won **2nd** place in the university’s Creativity competition. You can learn more in my LinkedIn post [here](https://www.linkedin.com/posts/lukasz-jalocha_deepfakes-are-getting-better-but-so-are-activity-7398331277914849281-DL--?utm_source=share&utm_medium=member_desktop&rcm=ACoAADrGqnsBArzAtd3SNxhPE789REHTHj7jMjQ).
          
          I was also active in a medical-informatics AI research club, where I worked under a professor’s supervision to experiment with algorithms for classifying cells from medical images.
      - layout: left
        title: University of Lower Silesia (DSW)
        caption: 2025 - Present
        sub_title: Master IT Project Management
        description: |
          I am currently beginning my part-time Master’s studies at DSW. My goal is to strengthen my competencies beyond technical skills and prepare for future opportunities in leadership roles, including team management and guiding engineering initiatives.

  - title: A Little More About Me
    layout: text
    content: |
      Outside of software engineering, I enjoy both home-based and physical activities. At home, I like **chess**, **cooking**, and **computer games**, which help me relax and stay mentally sharp. I also enjoy **disc golf** and **powerlifting**, which keep me active and competitive.
      
      <p></p>
      <p style="text-align: center; font-style: italic;">
      Here’s a photo of me playing disc golf 😄
      </p>
      
      <img src="images/disc-golf.jpg"
      alt="Disc-golf"
      title="Forest disc golf"
      style="display:block;margin-left:auto;margin-right:auto;width:50%;">

  - title: Downloads
    layout: text
    content: |
      [📄 Download CV (PDF)](files/Lukasz_Jalocha_CV.pdf)


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
